language: node_js
node_js:
  - lts/*

notifications:
  email:
    recipients:
      - $EMAIL
    on_success: change
    on_failure: always

install:
  - npm ci

script:
  # Build
  - npm run build
  # Test
  - npm test

cache:
  npm: true
  directories:
    - npm
    - node_modules
